version: '3.8'

services:
  watchdog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-watchdog
    restart: unless-stopped
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - RCON_PORT=${RCON_PORT}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - OFFLINE_INTERVAL=${OFFLINE_INTERVAL}
      - EMPTY_THRESHOLD=${EMPTY_THRESHOLD}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
